# Run against all files: pre-commit run --all-files
# Update revisions: pre-commit autoupdate
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.5.3
    hooks:
      - id: prettier
        types_or: [yaml, json]

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.4
    hooks:
      # Update the uv lockfile
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      # Check adherence to conventional commits specification
      - id: ensure-conventional-commit-style
        name: ensure-conventional-commit-style
        entry: ./scripts/ensure_conventional_commit_style.sh
        language: system
        stages: [commit-msg]
