name: Continuous integration

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "*.md"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup | Install uv # https://docs.astral.sh/uv/guides/integration/github/#using-uv-in-github-actions
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
        with:
          enable-cache: false

      - name: Setup | Install Python # https://docs.astral.sh/uv/guides/integration/github/#setting-up-python
        run: uv python install

      - name: Setup | Install pre-commit # https://pre-commit.com/#usage-in-continuous-integration
        run: uv tool install pre-commit

      - name: Run | Test
        run: make test
